name: Ruby

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.1']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
    uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    env:
      G_ENV: g_env
    - name: name1
      env:
        NAME1_ENV: name1_env
      run: |
        echo ${{ env.G_ENV }}
        echo ${{ env.NAME1_ENV }}
    - name: name2
      run: |
        echo ${{ env.G_ENV }}
        echo ${{ env.NAME1_ENV }}
    - name: name3
      run: |
        echo ${{ env.G_ENV }}
        echo ${{ env.NAME1_ENV }}
